schema_version: 1

context:
  python_min: 3.10
  name: paradoc
  version: 0.3.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Krande/paradoc/archive/v${{ version }}.tar.gz
  sha256: b82ee4c9bc990e339f3341559dd9bd464efb3cf3c7105af5d8ef35920a0b03d4

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - paradoc=paradoc.cli_app:app

requirements:
  host:
    - python 3.10.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pandoc 3.1.2.*
    - pandoc-crossref 0.3.16.*
    - pypandoc 1.12.*
    - python-docx
    - docxcompose
    - numpy
    - pandas
    - openpyxl
    - tabulate
    - svgwrite
    - pytexit
    - typer
    - if: unix
      then: __unix
    - if: win
      then: __win
    - if: win
      then: pywin32

tests:
  - python:
      pip_check: false
  - files:
      source:
        - tests
        - files
    requirements:
      run:
        - pytest
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - cd tests
      - pytest

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A Python library for Parametric Documentation
  homepage: https://github.com/krande/paradoc

extra:
  recipe-maintainers:
    - Krande
